### ISSUE TITLE
关于数据集的一点问题。

### ISSUE THREAD

**Issue by shipengai** [RLHF-V/RLHF-V#1]
在文件RLHF-V-Hall_v0-1401.tsv和RLHF-V-Hall_v0_dpo_with_rlhf-v-sft_logp_train-1401.tsv有7列，每一列表示什么？

**Comment by Haoye17** [comment]
您好，非常感谢您关注我们的工作！
为了比较好的解释数据集的情况，我们在huggingface的[数据集](https://huggingface.co/datasets/HaoyeZhang/RLHF-V-Hall_v0)项目下更新了readme文件，在这里附上数据文件每一列的含义：

- 0 `dataset_name`: 我们为每个数据设置了唯一的数据集名称，以便区分。
- 1 `img_b64_buffer`: base64格式的图片。
- 2 `text_b64`: base64格式的文本信息，对`RLHF-V-Hall_v0-1401.tsv`而言，包括`question`, `chosen`, `rejected`；对`RLHF-V-Hall_v0_dpo_with_rlhf-v-sft_logp_train-1401.tsv`而言，包括`question`, `chosen`, `rejected`, 以及使用我们的SFT模型生成的`reference_model_logp`。
- 3 `origin_dataset`: 原始标注数据来源的数据集名称，在训练中不会使用。
- 4 `origin_split`: 数据的meta信息，包括生成数据所用模型名称，以及问题类型（即 `detailed_description` 或 `question_answering`）
- 5 `origin_split_inner_idx`: 数据条目的index信息
- 6 `image_path`: 图片的coco_id

如果您在使用数据集或者代码方面有任何其他问题，欢迎随时提问 ~

**Comment by wnzhyee** [comment]
@Haoye17 Hi, if i want to try this method on my own data, should i prepare the dataset format like this? Now if i have the data dict like {'dataset_name':"xxx", "image":"xxx", "text":"xxx", ...} and is not base64 format, should i transfer these data to base64 and save to tsv file? What does the lineidx file mean?

**Comment by Haoye17** [comment]
@wnzhyee Hi, sorry for answering late! 

If you want to directly use the dataset provided in our project, you do need to convert your data to tsv file. The basic idea for the .lineidx file is to save the number of bytes between the start of the file and the start of the current line so that it can directly access each line without having to load everything into memory. It is especially useful when the input data is extremely large.

 To convert a file into the .tsv format, we mainly depend on the script provided [here](https://github.com/thunlp/Muffin/blob/main/muffin/data/tsv_file_op.py). We also uploaded a demo that can convert a Pandas Dataframe into the TSV format we used. You can refer to `convert_parquet_to_tsv.py`.
 
 If there are any other questions, please feel free to ask~

**Comment by wnzhyee** [comment]
@Haoye17 thanks very much!

**Comment by Cooperx521** [comment]
@Haoye17 Hi, I hope this message finds you well. I've downloaded a file from [google drive](https://drive.google.com/drive/folders/1iJ9FvI2ENK9xjN1nAFMgyB5zSTTL1BE6), but it looks like messy code as the picture shows. I'm curious about why the format differs significantly from the data on [Hugginface](https://huggingface.co/datasets/HaoyeZhang/RLHF-V-Dataset), is it normal? And what's the difference betweet them?
![image](https://github.com/RLHF-V/RLHF-V/assets/131770126/bc7b8f57-1838-4c57-89e2-b72bb2efe35c)
