### ISSUE TITLE
corrections & hallucinations

### ISSUE THREAD

**Issue by eyuansu62** [RLHF-V/RLHF-V#4]
Great job, thank you for writing this paper; it was very intriguing and informative. I have a question that arose during my reading.
The paper said you collected the segment-level corrections & hallucinations. But I do not find this kind of information in the dataset.

**Comment by Haoye17** [comment]
Hi @eyuansu62 ! Sorry for the delay and thank you for acknowledging our work! 

Regarding the segment correction mentioned in our paper, what we mean is that during the collection of annotated data, we adopt a method of modifying only the hallucination parts of the sentences, rather than rewriting the answers entirely. 

A simple visualization for the segment-level corrections in our data is as follows:

<img width="952" alt="image" src="https://github.com/RLHF-V/RLHF-V/assets/42668396/3c0e3bd0-6640-43fe-b23f-1db79eb3e812">

Hope this is helpful to you! If there are further questions, do not hesitate to ask ~

**Comment by eyuansu62** [comment]
when you calculate the loss, you need find the changed overlap part of pos ans & neg ans firstly?

**Comment by Haoye17** [comment]
Yes, and we provide the diff finding code [here](https://github.com/thunlp/Muffin/blob/main/utils/diff_lib.py).
